Interacao-Humano-Computador/2021.1-Prefeitura-de-Concordia

- .github/workflow/ci.yml
- mkdocs.yml
- Implementação do mkdocs para a documentação e deploy automatico. 
```bash
$ pip install mkdocs-material
$ mkdocs serve
```
- #3 
* Implementação do mkdocs
* deploy automatico
> #3 Adicionado mkdocs e deploy automatico 

- docs/apresentacoes/p1.md
- mkdocs.yml
- Adição do vídeo do primeiro ponto de controle
- #7 
- Alteração da rota no mkdocs
> #7 Documento do primeiro ponto de controle

- docs/analiseTarefas/klm.md
- mkdocs.yml
- Adição do documento contendo a análise de tarefas KLM-GOMS.
- #23 
-  Adição do documento klm.md
- Adição de duas análises KLM
- Alteração do mkdocs.yml, inclusão do klm.md na navegação
> #23 Análise de tarefas KLM

- docs/apresentacoes/p1.md
- docs/apresentacoes/p2.md
- mkdocs.yml
- Adição do ponto de controle 2
- #32
- Adição do vídeo
- Adição dos slides
> #32 Adicionando documento do ponto de controle 2

- docs/analiseRequisitos/personas.md
- De acordo com o feedback do professor e monitor, foi adicionado o elenco de personas
- #39
- Adicionando elenco de personas
> #39 Elenco de personas

- docs/analiseRequisitos/metasUsabilidade.md
- mkdocs.yml
- Documentação das metas de usabilidade do domínio da Prefeitura de Concórdia
- #36 
- Documentação de cada meta de usabilidade
- Criação de subtópico "Perfil de Usuário" em "Análise de Requisitos"
> #36 Documento das Metas de Usabilidade

- docs/apresentacoes/p1.md
- docs/apresentacoes/p2.md
- docs/apresentacoes/p3.md
- mkdocs.yml
- Adição do ponto de controle 3
- #44
- Adição do vídeo
- Adição dos slides
> #44 Documentação 3 ponto de controle

- docs/analiseTarefas/planejamento.md
- mkdocs.yml
- Adição do documento contendo o planejamento da avaliação da análise de tarefas
- #47 
- Altração na estrutura da wiki
> #47 Planejamento análise de tarefas

- docs/nivel1/planejamento.md
- mkdocs.yml
- Adição do documento contendo o planejamento da avaliação dos storyboards
- #46 
- Altração na estrutura da wiki
> #46 Planejamento storyboards

- docs/apresentacoes/p5.md
- mkdocs.yml
- Adição do ponto de controle 4
- #62 
- Adição do vídeo
- Adição dos slides
> #62 Documentação 5 ponto de controle

- docs/nivel2/planejamento.md
- mkdocs.yml
- Adição do documento contendo o planejamento da avaliação do protótipo de baixa fidelidade
- #54 
- Altração na estrutura da wiki
> #54 Planejamento do Protótipo de Baixa Fidelidade

- docs/nivel2/prototipo.md
- mkdocs.yml
- Adição do documento contendo o protótipo de baixa fidelidade
- #53
- Criação do documento
- Adição do protótipo (figma)
- Adição das páginas (figma)
> #53 Prototipação de baixa fidelidade

- docs/verificacao/storyboards.md
- mkdocs.yml
- Adição da verificação dos storyboards
- #78 
- Adição da verificação sobre o storyboard
> #78 Verificação dos storyboards

- docs/verificacao/caracteristicas_da_plataforma.md
- docs/verificacao/introducao.md
- docs/verificacao/template_verificacao.md
- mkdocs.yml
- Adição da verificação das características da plataforma
- #75
- Adição da introdução sobre verificação
- Adição de template para docs de verificação
- Adição da verificação sobre características da plataforma
- Modificação do mkdocs.yml
> #75 Verificação características da plataforma

- docs/nivel2/planejamento.md
- docs/nivel3/planejamento.md
- mkdocs.yml
- Adição do planejamento de avaliação do protótipo de alta fidelidade
- #68
- Adição do planejamento 
- Modificação do mkdocs
- Correção planejamento 2
> #68 Planejamento do protótipo alta fidelidade

- docs/nivel3/prototipo.md
- mkdocs.yml
- Adicionando prototipo de alta fidelidade
#67 
* Criação do documento
* Prototipação da página principal
* Prototipação da página de notícia e da notícia em sí
* Prototipação da página de história (contendo as 4 opções)
* Prototipação de uma página que contenha um formulário de preenchimento (iluminação pública, falta de água, procon, etc...)
> #67 Prototipação de alta fidelidade

- docs/verificacao/prototipo_alta_fidelidade.md
- mkdocs.yml
- Adição da verificação do protótipo de alta fidelidade
- #82 
- Adição da verificação sobre o protótipo de alta fidelidade
> #82 Verificação do protótipo de alta fidelidade

- docs/apresentacoes/p6.md
- mkdocs.yml
- Adição do ponto de controle 6
- #90 
- Adição do vídeo
- Adição dos slides
> #90 Documentação 6 ponto de controle

- docs/nivel2/avaliacoesPrototipo/entrevista1.md
- docs/nivel2/avaliacoesPrototipo/entrevista2.md
- docs/nivel2/planejamento.md
- Documento contendo as entrevistas do protótipo de baixa fidelidade.
- #66 
- Adição de 2 entrevistas
- Adição dos documentos
- Adição dos links no planejamento
> #66 Adição entrevistas do protótipo de baixa fidelidade

- docs/verificacao/planejamento_prototipo_baixa.md
- mkdocs.yml
-  PR que entrega a verificação do planejamento e avaliação do protótipo de baixa fidelidade
- #81 
- Adição da verificação sobre o documento de  planejamento e avaliação do protótipo de baixa fidelidade
> #81 Verificacao planejamento avaliacao baixa fidelidade

- docs/verificacao/planejamento_storyboard.md
- mkdocs.yml
-  PR que entrega a verificação do planejamento e avaliação do storyboard
- #79 
- Adição da verificação sobre o documento de  planejamento e avaliação do storyboard
> #79 Verificação planejamento storyboard

- docs/verificacao/planejamento-avaliaca-alta-fidelidade.md
- mkdocs.yml
-  PR que entrega a verificação do planejamento e avaliação do protótipo de alta fidelidade
- #83 
- Adição da verificação sobre o documento de  planejamento e avaliação do protótipo de alta fidelidade
> #83 Verificação do planejamento e avaliação do protótipo de alta fidelidade
